export const DATA_GET_DATA_REQUEST = 'DATA_GET_DATA_REQUEST'
export const DATA_GET_DATA_SUCCESS = 'DATA_GET_DATA_SUCCESS'
export const DATA_GET_DATA_FAIL = 'DATA_GET_DATA_FAIL'

export const DATA_GET_DATA_ID_REQUEST = 'DATA_GET_DATA_ID_REQUEST'
export const DATA_GET_DATA_ID_SUCCESS = 'DATA_GET_DATA_ID_SUCCESS'
export const DATA_GET_DATA_ID_FAIL = 'DATA_GET_DATA_ID_FAIL'


export const DATA_GET_INFO_REQUEST = 'DATA_GET_INFO_REQUEST'
export const DATA_GET_INFO_SUCCESS = 'DATA_GET_INFO_SUCCESS'
export const DATA_GET_INFO_FAIL = 'DATA_GET_INFO_FAIL'

export const DATA_DELETE_DATA_ID_REQUEST = 'DATA_DELETE_DATA_ID_REQUEST'
export const DATA_DELETE_DATA_ID_SUCCESS = 'DATA_DELETE_DATA_ID_SUCCESS'
export const DATA_DELETE_DATA_ID_FAIL = 'DATA_DELETE_DATA_ID_FAIL'