export const DATA_UPLOAD_REQUEST = 'DATA_UPLOAD_REQUEST'
export const DATA_UPLOAD_SUCCESS = 'DATA_UPLOAD_SUCCESS'
export const DATA_UPLOAD_FAIL = 'DATA_UPLOAD_FAIL'

export const DATA_GET_DATA_REQUEST = 'DATA_UPLOAD_REQUEST'
export const DATA_GET_DATA_SUCCESS = 'DATA_UPLOAD_SUCCESS'
export const DATA_GET_DATA_FAIL = 'DATA_UPLOAD_FAIL'