export const DATA_UPLOAD_REQUEST = 'DATA_UPLOAD_REQUEST'
export const DATA_UPLOAD_SUCCESS = 'DATA_UPLOAD_SUCCESS'
export const DATA_UPLOAD_FAIL = 'DATA_UPLOAD_FAIL'

export const DATA_GET_DATA_REQUEST = 'DATA_GET_DATA_REQUEST'
export const DATA_GET_DATA_SUCCESS = 'DATA_GET_DATA_SUCCESS'
export const DATA_GET_DATA_FAIL = 'DATA_GET_DATA_FAIL'

export const DATA_GET_DATA_ID_REQUEST = 'DATA_GET_DATA_ID_REQUEST'
export const DATA_GET_DATA_ID_SUCCESS = 'DATA_GET_DATA_ID_SUCCESS'
export const DATA_GET_DATA_ID_FAIL = 'DATA_GET_DATA_ID_FAIL'


export const DATA_GET_DEVICES_REQUEST = 'DATA_GET_DEVICES_REQUEST'
export const DATA_GET_DEVICES_SUCCESS = 'DATA_GET_DEVICES_SUCCESS'
export const DATA_GET_DEVICES_FAIL = 'DATA_GET_DEVICES_FAIL'
